 CREATE TABLESPACE COURSES DATAFILE
 'C:\oraclexe\app\oracle\DBA\curso1.DBF' SIZE 50M
 
 CREATE PROFILE administrativo LIMIT
 SESSIONS_PER_USER               1
 IDLE_TIME                       25
 FAILED_LOGIN_ATTEMPTS           4;
 
CREATE USER Angel120892
IDENTIFIED BY 12345
DEFAULT TABLESPACE COURSES
QUOTA 30MB ON COURSES;

CREATE USER Angel120892
IDENTIFIED BY 12345
DEFAULT tablespace COURSES
QUOTA 30M ON COURSES
PROFILE administrativo;

DROP USER Angel120892;

SELECT * FROM SYS.DBA_USERS;

GRANT CREATE SESSION TO Angel120892;

GRANT DBA TO DBA_Angel120892;


CREATE TABLE COURSES (
  ID number NOT NULL,
  name varchar(255) NOT NULL,
  code varchar(255) NOT NULL,
  date_start  DATE NOT NULL,
  date_end DATE NOT NULL,
);


select * from all_tables;

COURSES(id, name, code, date_start, date_end) 

STUDENTS(id, first_name, last_name, date_of_birth, city, address) 

ATTENDANCE(id, student_id, course_id, attendance_date) 

ANSWERS(id, number_of_question, answer)


//CREACION DE TABLAS

CREATE TABLE ANGEL120892.COURSES (
  ID INT NOT NULL, 
 NAME VARCHAR2(255) NOT NULL,
 CODE VARCHAR2(255) NOT NULL,
 START_DATE DATE NOT NULL,
 END_DATE DATE NOT NULL 
);

SELECT * FROM ANGEL120892.COURSES;

CREATE TABLE ANGEL120892.STUDENTS (
ID INT NOT NULL, 
first_name VARCHAR2(255) NOT NULL,
last_name VARCHAR2(255) NOT NULL,
date_of_birth VARCHAR (255) NOT NULL,
city VARCHAR2 (255) NOT NULL,
address VARCHAR2 (255) NOT NULL
);

CONNECT  ANGEL120892;

SELECT * FROM ANGEL120892.STUDENTS;

drop table ANGEL120892.COURSES;

select * from all_tables;

CREATE TABLE ANGEL120892.ATTENDACE (
ID INT NOT NULL, 
student_id INT NOT NULL,
course_id INT NOT NULL,
attendance_date date NOT NULL
);

select * from ANGEL120892.ATTENDACE;


CREATE TABLE ANGEL120892.ANSWERS (
ID INT NOT NULL, 
number_of_question INT NOT NULL,
answer INT NOT NULL
);

select * from ANGEL120892.ANSWERS;

// add constrait

ALTER TABLE ANGEL120892.STUDENTS
ADD CONSTRAINT STUDENTS_PK PRIMARY KEY 
(
  ID 
)
ENABLE;

ALTER TABLE ANGEL120892.COURSES
ADD CONSTRAINT COURSES_PK PRIMARY KEY 
(
  ID 
)
ENABLE;

ALTER TABLE ANGEL120892.ATTENDACE
ADD CONSTRAINT ATTENDACE_PK PRIMARY KEY 
(
  ID 
)
ENABLE;


ALTER TABLE ANGEL120892.ANSWERS
ADD CONSTRAINT ANSWERS_PK PRIMARY KEY 
(
  ID 
)
ENABLE;

